# Generated by Django 4.1.2 on 2022-11-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=350)),
            ],
        ),
    ]
